#spring.profiles.active=@activatedProperties@
spring.profiles.active=local

# MyBatis \uC124\uC815
mybatis.mapper-locations=classpath:mapper/**/*.xml

# MyBatis SQL Log Print
logging.level.com.prafta=WARN
logging.level.org.mybatis=DEBUG
logging.level.org.apache.ibatis=DEBUG

# JDBC Parameter
logging.level.jdbc.sqlonly=DEBUG
logging.level.jdbc.sqltiming=DEBUG

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

spring.mvc.pathmatch.matching-strategy=ant_path_matcher
mybatis.configuration.map-underscore-to-camel-case=true

# Holiday API KEY
holiday.api.base-url=${HOLIDAY_API_BASE_URL:http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo}
holiday.api.service-key=${HOLIDAY_API_SERVICE_KEY:}
holiday.api.num-of-rows=${HOLIDAY_API_NUM_OF_ROWS:100}
holiday.api.type=${HOLIDAY_API_TYPE:json}