# application-local.properties
#spring.datasource.url=jdbc:mysql://localhost:3306/prafta?serverTimezone=Asia/Seoul
spring.datasource.url=jdbc:p6spy:mysql://localhost:3306/prafta?serverTimezone=Asia/Seoul
spring.datasource.username=dev_prafta
spring.datasource.password=prafta12345!
#spring.datasource.username=root
#spring.datasource.password=praftadkagh1!
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.driver-class-name=com.p6spy.engine.spy.P6SpyDriver


mybatis.configuration.map-underscore-to-camel-case=true