-- ============================================================
-- DB 타임존 KST 전환 - 기존 UTC 데이터 +9h 보정 (tz-kst-cutover-1)
-- 생성일: 2026-08-30 / 런북: .claude/refs/DB타임존_KST전환_런북_2026-08-30.md
--
-- ★실행 전제(런북 §3 순서 엄수):
--   1) RDS 수동 스냅샷 생성 완료
--   2) 백엔드 앱 정지 상태
--   3) RDS 파라미터 그룹 time_zone=Asia/Seoul 적용 후 "새" Workbench 세션에서 실행
--   4) 아래 @CUTOVER_UTC 를 실제 값으로 교체했는지 확인
--
-- ★@CUTOVER_UTC = 운영 이관(개발 덤프 로드) 시점의 "UTC 벽시계".
--   AWS 콘솔 > RDS > prafta-db > 생성 시각(UTC)으로 확인해 기입한다.
--   이 시각 이후 벽시계의 행(=운영 라이브에서 NOW()/UTC 로 기록된 행)만 +9h 보정한다.
--   이전 행은 개발 DB(KST) 덤프 이식분이라 이미 KST — 보정 대상 아님.
--   (그레이존: 이관 직전 9시간 내 개발 기록 행은 +9h 과보정될 수 있으나 전부
--    실고객 이전 테스트 데이터라 수용 — 런북 §5)
--
-- ★보정 제외 컬럼(Java-KST 기록 - 절대 밀지 말 것, 본 파일에 미포함 확인됨):
--   tb_near_miss.OCCUR_DTIME / tb_cmpny_share_snapshot_nearmiss.OCCUR_DTIME
--
-- ★1회만 실행. 아래 마커 INSERT 가 중복 키로 실패하면 이미 실행된 것 - 전체 중단하라.
-- ============================================================

SET SQL_SAFE_UPDATES = 0;

-- 이중 실행 가드 마커(재실행 시 Duplicate entry 오류로 정지)
CREATE TABLE IF NOT EXISTS tz_migration_marker (
  STEP        varchar(100) NOT NULL COMMENT '마이그레이션 단계 식별자',
  EXECUTED_AT datetime     NOT NULL COMMENT '실행 시각(KST - 전환 후 실행되므로)',
  PRIMARY KEY (STEP)
) COMMENT='DB 타임존 KST 전환 마이그레이션 실행 마커';

-- ★★ 확정값 기입 완료(2026-08-30): RDS prafta-db 생성 시각 = 2026-07-18 11:14 KST = 02:14 UTC
--    (콘솔 실측 — 이 시각 이후 벽시계 행만 운영 라이브(UTC 기록)이므로 +9h 보정 대상)
SET @CUTOVER_UTC = '2026-07-18 02:14:00';

-- 가드 1: 플레이스홀더 미교체 차단 - 미교체 상태면 다중행 서브쿼리 오류(1242)로 즉시 정지된다.
--         (Workbench 기본 동작 = 오류 시 스크립트 중단. "계속 실행" 옵션을 켜지 말 것)
SELECT IF(@CUTOVER_UTC LIKE '{{%', (SELECT 1 UNION ALL SELECT 2), 1) AS placeholder_guard;

-- 가드 2: 유효한 DATETIME 인지 확인 - 파싱 불가 값이면 NULL 이 되어 아래 서브쿼리 오류로 정지.
SELECT IF(CAST(@CUTOVER_UTC AS DATETIME) IS NULL, (SELECT 1 UNION ALL SELECT 2), 1) AS datetime_guard;

START TRANSACTION;

-- 이중 실행 가드 마커: 재실행 시 Duplicate entry 오류로 정지.
--   트랜잭션 안에서 INSERT 하므로, 아래 UPDATE 도중 실패해 롤백되면 마커도 함께 사라져 재실행이 가능하다.
INSERT INTO tz_migration_marker (STEP, EXECUTED_AT) VALUES ('tz-kst-cutover-1-shift', NOW());

UPDATE tb_acct SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_acct SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_acct_legal_step SET DONE_DTIME = DONE_DTIME + INTERVAL 9 HOUR WHERE DONE_DTIME IS NOT NULL AND DONE_DTIME >= @CUTOVER_UTC;
UPDATE tb_acct_legal_step SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_acct_legal_step SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_acct_legal_step_master SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_acct_legal_step_master SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_acct_link SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_acct_link SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_ai_token_quota SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_ai_token_quota SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_ai_token_usage SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_ai_token_usage SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_aprv_line_preset SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_aprv_line_preset SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_aprv_line_preset_d SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_aprv_line_preset_d SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_attd_close SET CLOSE_DTIME = CLOSE_DTIME + INTERVAL 9 HOUR WHERE CLOSE_DTIME IS NOT NULL AND CLOSE_DTIME >= @CUTOVER_UTC;
UPDATE tb_attd_close SET UNCLOSE_DTIME = UNCLOSE_DTIME + INTERVAL 9 HOUR WHERE UNCLOSE_DTIME IS NOT NULL AND UNCLOSE_DTIME >= @CUTOVER_UTC;
UPDATE tb_attd_close SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_attd_close SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_attd_close_hist SET ACTION_DTIME = ACTION_DTIME + INTERVAL 9 HOUR WHERE ACTION_DTIME IS NOT NULL AND ACTION_DTIME >= @CUTOVER_UTC;
UPDATE tb_attd_close_hist SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_audit_log SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_auth_token SET ISSUED_DTIME = ISSUED_DTIME + INTERVAL 9 HOUR WHERE ISSUED_DTIME IS NOT NULL AND ISSUED_DTIME >= @CUTOVER_UTC;
UPDATE tb_auth_token SET EXPIRE_DTIME = EXPIRE_DTIME + INTERVAL 9 HOUR WHERE EXPIRE_DTIME IS NOT NULL AND EXPIRE_DTIME >= @CUTOVER_UTC;
UPDATE tb_auth_token SET REVOKED_DTIME = REVOKED_DTIME + INTERVAL 9 HOUR WHERE REVOKED_DTIME IS NOT NULL AND REVOKED_DTIME >= @CUTOVER_UTC;
UPDATE tb_auth_token SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_auth_token SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_baim_val_d SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_baim_val_m SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_chkpt_defect_action SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_chkpt_defect_action SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_chkpt_defect_action_hist SET ACTION_DTIME = ACTION_DTIME + INTERVAL 9 HOUR WHERE ACTION_DTIME IS NOT NULL AND ACTION_DTIME >= @CUTOVER_UTC;
UPDATE tb_chkpt_defect_action_hist SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_chkpt_inspect_answer SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_chkpt_inspect_answer SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_chkpt_inspect_answer_hist SET ACTION_DTIME = ACTION_DTIME + INTERVAL 9 HOUR WHERE ACTION_DTIME IS NOT NULL AND ACTION_DTIME >= @CUTOVER_UTC;
UPDATE tb_chkpt_inspect_answer_hist SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_chkpt_inspect_item SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_chkpt_inspect_item SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_chkpt_inspect_item_hist SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_chkpt_type_mgmt SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_chkpt_type_mgmt SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_relation SET PROCESS_DTIME = PROCESS_DTIME + INTERVAL 9 HOUR WHERE PROCESS_DTIME IS NOT NULL AND PROCESS_DTIME >= @CUTOVER_UTC;
UPDATE tb_cmpny_relation SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_relation SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_relation_hist SET ACTION_DTIME = ACTION_DTIME + INTERVAL 9 HOUR WHERE ACTION_DTIME IS NOT NULL AND ACTION_DTIME >= @CUTOVER_UTC;
UPDATE tb_cmpny_relation_hist SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_req SET PROCESS_DTIME = PROCESS_DTIME + INTERVAL 9 HOUR WHERE PROCESS_DTIME IS NOT NULL AND PROCESS_DTIME >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_req SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_req SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_snapshot SET CREATE_DTIME = CREATE_DTIME + INTERVAL 9 HOUR WHERE CREATE_DTIME IS NOT NULL AND CREATE_DTIME >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_snapshot SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_snapshot SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_snapshot_attd SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_snapshot_attd SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_snapshot_bundle SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_snapshot_nearmiss SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_snapshot_nearmiss SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_snapshot_risk SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_snapshot_risk SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_share_snapshot_risk_improve SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_std_work_policy SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_cmpny_std_work_policy SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_blacklist SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_blacklist SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_contract SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_contract SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_contract_sign SET SIGN_DTIME = SIGN_DTIME + INTERVAL 9 HOUR WHERE SIGN_DTIME IS NOT NULL AND SIGN_DTIME >= @CUTOVER_UTC;
UPDATE tb_daily_contract_sign SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_entry_request SET REQ_DTIME = REQ_DTIME + INTERVAL 9 HOUR WHERE REQ_DTIME IS NOT NULL AND REQ_DTIME >= @CUTOVER_UTC;
UPDATE tb_daily_entry_request SET PROC_DTIME = PROC_DTIME + INTERVAL 9 HOUR WHERE PROC_DTIME IS NOT NULL AND PROC_DTIME >= @CUTOVER_UTC;
UPDATE tb_daily_entry_request SET CONSUME_DTIME = CONSUME_DTIME + INTERVAL 9 HOUR WHERE CONSUME_DTIME IS NOT NULL AND CONSUME_DTIME >= @CUTOVER_UTC;
UPDATE tb_daily_entry_request SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_entry_request SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_link_mgmt SET EXPIRE_DTIME = EXPIRE_DTIME + INTERVAL 9 HOUR WHERE EXPIRE_DTIME IS NOT NULL AND EXPIRE_DTIME >= @CUTOVER_UTC;
UPDATE tb_daily_link_mgmt SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_link_mgmt SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_user SET PWD_LOCK_EXPIRE_DTIME = PWD_LOCK_EXPIRE_DTIME + INTERVAL 9 HOUR WHERE PWD_LOCK_EXPIRE_DTIME IS NOT NULL AND PWD_LOCK_EXPIRE_DTIME >= @CUTOVER_UTC;
UPDATE tb_daily_user SET LAST_LOGIN_DTIME = LAST_LOGIN_DTIME + INTERVAL 9 HOUR WHERE LAST_LOGIN_DTIME IS NOT NULL AND LAST_LOGIN_DTIME >= @CUTOVER_UTC;
UPDATE tb_daily_user SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_user SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_user_link_policy SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_user_link_policy SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_user_slot SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_user_slot SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_daily_user_slot_his SET OCCUPY_DTIME = OCCUPY_DTIME + INTERVAL 9 HOUR WHERE OCCUPY_DTIME IS NOT NULL AND OCCUPY_DTIME >= @CUTOVER_UTC;
UPDATE tb_daily_user_slot_his SET RELEASE_DTIME = RELEASE_DTIME + INTERVAL 9 HOUR WHERE RELEASE_DTIME IS NOT NULL AND RELEASE_DTIME >= @CUTOVER_UTC;
UPDATE tb_daily_user_slot_his SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_del_user SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_file_info SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_file_info SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_holiday SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_holiday SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_holiday_rule SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_holiday_rule SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_change_request SET CONFIRM_DATE = CONFIRM_DATE + INTERVAL 9 HOUR WHERE CONFIRM_DATE IS NOT NULL AND CONFIRM_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_change_request SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_change_request SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_conv2_backfill_bak SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_conv_policy_bak_fix480 SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_conv_policy_bak_fix480 SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_conversion_policy SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_conversion_policy SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_policy SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_policy SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_policy_history SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_promotion_log SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_promotion_log SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_refusal_log SET DETECT_DTIME = DETECT_DTIME + INTERVAL 9 HOUR WHERE DETECT_DTIME IS NOT NULL AND DETECT_DTIME >= @CUTOVER_UTC;
UPDATE tb_leave_refusal_log SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_refusal_log SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_remnant_cover SET RECLAIM_DATE = RECLAIM_DATE + INTERVAL 9 HOUR WHERE RECLAIM_DATE IS NOT NULL AND RECLAIM_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_remnant_cover SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_remnant_cover SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_type_mgmt SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_type_mgmt SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_usage_policy SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_leave_usage_policy SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_location_access_log SET ACCESS_DTIME = ACCESS_DTIME + INTERVAL 9 HOUR WHERE ACCESS_DTIME IS NOT NULL AND ACCESS_DTIME >= @CUTOVER_UTC;
-- [security Medium #2] SMS_VERIFIED_AT 은 2026-08-30 CONVERT_TZ 수정 배포 이후부터 "이미 KST"로 적재된다.
--   그런 행(같은 행의 ACCESS_DTIME(UTC)보다 약 +9h 큼)을 또 밀면 이중 밀림이므로,
--   UTC 로 적재된 행(인증시각이 열람시각 이전 ±1h 이내)만 보정한다. 이미 KST 인 행은 제외.
UPDATE tb_location_access_log SET SMS_VERIFIED_AT = SMS_VERIFIED_AT + INTERVAL 9 HOUR WHERE SMS_VERIFIED_AT IS NOT NULL AND SMS_VERIFIED_AT >= @CUTOVER_UTC AND SMS_VERIFIED_AT < ACCESS_DTIME + INTERVAL 1 HOUR;
UPDATE tb_location_access_log SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_near_miss SET REPORT_DTIME = REPORT_DTIME + INTERVAL 9 HOUR WHERE REPORT_DTIME IS NOT NULL AND REPORT_DTIME >= @CUTOVER_UTC;
UPDATE tb_near_miss SET REVIEW_DTIME = REVIEW_DTIME + INTERVAL 9 HOUR WHERE REVIEW_DTIME IS NOT NULL AND REVIEW_DTIME >= @CUTOVER_UTC;
UPDATE tb_near_miss SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_near_miss SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_noti_outbox SET SENT_DATE = SENT_DATE + INTERVAL 9 HOUR WHERE SENT_DATE IS NOT NULL AND SENT_DATE >= @CUTOVER_UTC;
UPDATE tb_noti_outbox SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_noti_outbox SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_notice SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_notice SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_notice_file SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_notice_target SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_notice_user_ack SET LAST_READ_DATE = LAST_READ_DATE + INTERVAL 9 HOUR WHERE LAST_READ_DATE IS NOT NULL AND LAST_READ_DATE >= @CUTOVER_UTC;
UPDATE tb_notice_user_ack SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_notice_user_ack SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_ai_derivation SET LAST_DERIVE_DATE = LAST_DERIVE_DATE + INTERVAL 9 HOUR WHERE LAST_DERIVE_DATE IS NOT NULL AND LAST_DERIVE_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_ai_derivation SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_ai_derivation SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_assessment SET INIT_ASSESS_DATE = INIT_ASSESS_DATE + INTERVAL 9 HOUR WHERE INIT_ASSESS_DATE IS NOT NULL AND INIT_ASSESS_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_assessment SET REVAL_ASSESS_DATE = REVAL_ASSESS_DATE + INTERVAL 9 HOUR WHERE REVAL_ASSESS_DATE IS NOT NULL AND REVAL_ASSESS_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_assessment SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_assessment SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_improvement_item SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_improvement_item SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_near_miss_link SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_near_miss_link SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_site_hazard SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_site_hazard SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_type SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_risk_type SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_sch_mgmt SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_sch_mgmt SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_sch_mgmt_hist SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_shift_sch_assign_mgmt SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_shift_sch_assign_mgmt SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_shift_sch_mgmt SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_shift_sch_mgmt SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_shift_sch_ptrn_mgmt SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_shift_sch_ptrn_mgmt SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_shift_sch_team_meta_info SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_shift_sch_team_meta_info SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_shift_sch_team_mgmt SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_shift_sch_team_mgmt SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_shift_sch_team_user SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_shift_sch_team_user SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_site SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_site_link SET PROCESS_DTIME = PROCESS_DTIME + INTERVAL 9 HOUR WHERE PROCESS_DTIME IS NOT NULL AND PROCESS_DTIME >= @CUTOVER_UTC;
UPDATE tb_site_link SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_site_link SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_site_link SET CHKPT_LINK_DTIME = CHKPT_LINK_DTIME + INTERVAL 9 HOUR WHERE CHKPT_LINK_DTIME IS NOT NULL AND CHKPT_LINK_DTIME >= @CUTOVER_UTC;
UPDATE tb_site_node SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_site_node SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_sms_auth_code SET FAIL_LOCKED_AT = FAIL_LOCKED_AT + INTERVAL 9 HOUR WHERE FAIL_LOCKED_AT IS NOT NULL AND FAIL_LOCKED_AT >= @CUTOVER_UTC;
UPDATE tb_sms_auth_code SET EXPIRED_AT = EXPIRED_AT + INTERVAL 9 HOUR WHERE EXPIRED_AT IS NOT NULL AND EXPIRED_AT >= @CUTOVER_UTC;
UPDATE tb_sms_auth_code SET SEND_DATE = SEND_DATE + INTERVAL 9 HOUR WHERE SEND_DATE IS NOT NULL AND SEND_DATE >= @CUTOVER_UTC;
UPDATE tb_sms_auth_code SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_sms_auth_code SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_sms_send_policy SET KILL_SWITCH_AT = KILL_SWITCH_AT + INTERVAL 9 HOUR WHERE KILL_SWITCH_AT IS NOT NULL AND KILL_SWITCH_AT >= @CUTOVER_UTC;
UPDATE tb_sms_send_policy SET KILL_SWITCH_RELEASE_AT = KILL_SWITCH_RELEASE_AT + INTERVAL 9 HOUR WHERE KILL_SWITCH_RELEASE_AT IS NOT NULL AND KILL_SWITCH_RELEASE_AT >= @CUTOVER_UTC;
UPDATE tb_sms_send_policy SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_sms_send_policy SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_sms_verify_attempt SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_syst_auth_menu SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_syst_auth_menu SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_syst_menu_d SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_syst_menu_d SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_syst_menu_m SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_syst_menu_m SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_syst_val_d SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_syst_val_m SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_attendance SET ENTRY_AT = ENTRY_AT + INTERVAL 9 HOUR WHERE ENTRY_AT IS NOT NULL AND ENTRY_AT >= @CUTOVER_UTC;
UPDATE tb_tbm_attendance SET EXIT_AT = EXIT_AT + INTERVAL 9 HOUR WHERE EXIT_AT IS NOT NULL AND EXIT_AT >= @CUTOVER_UTC;
UPDATE tb_tbm_attendance SET STATUS_UPDATED_AT = STATUS_UPDATED_AT + INTERVAL 9 HOUR WHERE STATUS_UPDATED_AT IS NOT NULL AND STATUS_UPDATED_AT >= @CUTOVER_UTC;
UPDATE tb_tbm_attendance SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_attendance SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_attendance_event SET EVENT_TIME = EVENT_TIME + INTERVAL 9 HOUR WHERE EVENT_TIME IS NOT NULL AND EVENT_TIME >= @CUTOVER_UTC;
UPDATE tb_tbm_attendance_event SET SERVER_RECEIVED_AT = SERVER_RECEIVED_AT + INTERVAL 9 HOUR WHERE SERVER_RECEIVED_AT IS NOT NULL AND SERVER_RECEIVED_AT >= @CUTOVER_UTC;
UPDATE tb_tbm_attendance_event SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_edu_mtrl SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_edu_mtrl SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_edu_mtrl SET GEN_AT = GEN_AT + INTERVAL 9 HOUR WHERE GEN_AT IS NOT NULL AND GEN_AT >= @CUTOVER_UTC;
UPDATE tb_tbm_edu_mtrl_item SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_edu_mtrl_item SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_edu_mtrl_item SET AI_ANALYZED_AT = AI_ANALYZED_AT + INTERVAL 9 HOUR WHERE AI_ANALYZED_AT IS NOT NULL AND AI_ANALYZED_AT >= @CUTOVER_UTC;
UPDATE tb_tbm_pwd_fail SET ATTEMPTED_AT = ATTEMPTED_AT + INTERVAL 9 HOUR WHERE ATTEMPTED_AT IS NOT NULL AND ATTEMPTED_AT >= @CUTOVER_UTC;
UPDATE tb_tbm_pwd_fail SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_session SET OPENED_AT = OPENED_AT + INTERVAL 9 HOUR WHERE OPENED_AT IS NOT NULL AND OPENED_AT >= @CUTOVER_UTC;
UPDATE tb_tbm_session SET PREP_START_AT = PREP_START_AT + INTERVAL 9 HOUR WHERE PREP_START_AT IS NOT NULL AND PREP_START_AT >= @CUTOVER_UTC;
UPDATE tb_tbm_session SET STARTED_AT = STARTED_AT + INTERVAL 9 HOUR WHERE STARTED_AT IS NOT NULL AND STARTED_AT >= @CUTOVER_UTC;
UPDATE tb_tbm_session SET ENDED_AT = ENDED_AT + INTERVAL 9 HOUR WHERE ENDED_AT IS NOT NULL AND ENDED_AT >= @CUTOVER_UTC;
UPDATE tb_tbm_session SET CANCELLED_AT = CANCELLED_AT + INTERVAL 9 HOUR WHERE CANCELLED_AT IS NOT NULL AND CANCELLED_AT >= @CUTOVER_UTC;
UPDATE tb_tbm_session SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_session SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_session_content SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_session_risk SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_session_share SET DESIGNATED_DTIME = DESIGNATED_DTIME + INTERVAL 9 HOUR WHERE DESIGNATED_DTIME IS NOT NULL AND DESIGNATED_DTIME >= @CUTOVER_UTC;
UPDATE tb_tbm_session_share SET RELEASED_DTIME = RELEASED_DTIME + INTERVAL 9 HOUR WHERE RELEASED_DTIME IS NOT NULL AND RELEASED_DTIME >= @CUTOVER_UTC;
UPDATE tb_tbm_session_share SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_session_share SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_session_state SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_tbm_session_state SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_terms SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_terms SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_terms_id_version SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_terms_user_agr_hist SET ACTION_DTIME = ACTION_DTIME + INTERVAL 9 HOUR WHERE ACTION_DTIME IS NOT NULL AND ACTION_DTIME >= @CUTOVER_UTC;
UPDATE tb_terms_user_agr_hist SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_terms_user_agr_mgmt SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user SET DEFAULT_SCH_SET_DATE = DEFAULT_SCH_SET_DATE + INTERVAL 9 HOUR WHERE DEFAULT_SCH_SET_DATE IS NOT NULL AND DEFAULT_SCH_SET_DATE >= @CUTOVER_UTC;
UPDATE tb_user SET PWD_LOCK_EXPIRE_DTIME = PWD_LOCK_EXPIRE_DTIME + INTERVAL 9 HOUR WHERE PWD_LOCK_EXPIRE_DTIME IS NOT NULL AND PWD_LOCK_EXPIRE_DTIME >= @CUTOVER_UTC;
UPDATE tb_user SET PWD_CHG_DTIME = PWD_CHG_DTIME + INTERVAL 9 HOUR WHERE PWD_CHG_DTIME IS NOT NULL AND PWD_CHG_DTIME >= @CUTOVER_UTC;
UPDATE tb_user SET LAST_LOGIN_DTIME = LAST_LOGIN_DTIME + INTERVAL 9 HOUR WHERE LAST_LOGIN_DTIME IS NOT NULL AND LAST_LOGIN_DTIME >= @CUTOVER_UTC;
UPDATE tb_user SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_attd_gps SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_attd_hist SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_attd_mgmt SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_attd_mgmt SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_attd_req SET PROCESS_DATE = PROCESS_DATE + INTERVAL 9 HOUR WHERE PROCESS_DATE IS NOT NULL AND PROCESS_DATE >= @CUTOVER_UTC;
UPDATE tb_user_attd_req SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_attd_req SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_attd_req_approval SET APPROVAL_DATE = APPROVAL_DATE + INTERVAL 9 HOUR WHERE APPROVAL_DATE IS NOT NULL AND APPROVAL_DATE >= @CUTOVER_UTC;
UPDATE tb_user_attd_req_approval SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_attd_req_approval SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_device SET LAST_LOGIN_DTIME = LAST_LOGIN_DTIME + INTERVAL 9 HOUR WHERE LAST_LOGIN_DTIME IS NOT NULL AND LAST_LOGIN_DTIME >= @CUTOVER_UTC;
UPDATE tb_user_device SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_device SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_device_login_hist SET LOGIN_DTIME = LOGIN_DTIME + INTERVAL 9 HOUR WHERE LOGIN_DTIME IS NOT NULL AND LOGIN_DTIME >= @CUTOVER_UTC;
UPDATE tb_user_device_login_hist SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_device_occupancy_anomaly SET DETECTED_DTIME = DETECTED_DTIME + INTERVAL 9 HOUR WHERE DETECTED_DTIME IS NOT NULL AND DETECTED_DTIME >= @CUTOVER_UTC;
UPDATE tb_user_device_occupancy_anomaly SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_hire_date_history SET APPLIED_DATE = APPLIED_DATE + INTERVAL 9 HOUR WHERE APPLIED_DATE IS NOT NULL AND APPLIED_DATE >= @CUTOVER_UTC;
UPDATE tb_user_hire_date_history SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_leave_grant SET EXPIRE_DATE = EXPIRE_DATE + INTERVAL 9 HOUR WHERE EXPIRE_DATE IS NOT NULL AND EXPIRE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_leave_grant SET CANCEL_DATE = CANCEL_DATE + INTERVAL 9 HOUR WHERE CANCEL_DATE IS NOT NULL AND CANCEL_DATE >= @CUTOVER_UTC;
UPDATE tb_user_leave_grant SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_leave_grant SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_leave_use SET CANCEL_DATE = CANCEL_DATE + INTERVAL 9 HOUR WHERE CANCEL_DATE IS NOT NULL AND CANCEL_DATE >= @CUTOVER_UTC;
UPDATE tb_user_leave_use SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_leave_use SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_menu_favorite SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_overtime_mgmt SET REDUCED_CLAIM_DTIME = REDUCED_CLAIM_DTIME + INTERVAL 9 HOUR WHERE REDUCED_CLAIM_DTIME IS NOT NULL AND REDUCED_CLAIM_DTIME >= @CUTOVER_UTC;
UPDATE tb_user_overtime_mgmt SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_overtime_mgmt SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_push_setting SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_push_setting SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_service_credit SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_service_credit SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_site_auth SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_site_auth SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_std_work_hours SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_std_work_hours SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_transfer_reservation SET NOTICE_ACK_DATE = NOTICE_ACK_DATE + INTERVAL 9 HOUR WHERE NOTICE_ACK_DATE IS NOT NULL AND NOTICE_ACK_DATE >= @CUTOVER_UTC;
UPDATE tb_user_transfer_reservation SET EXECUTED_DATE = EXECUTED_DATE + INTERVAL 9 HOUR WHERE EXECUTED_DATE IS NOT NULL AND EXECUTED_DATE >= @CUTOVER_UTC;
UPDATE tb_user_transfer_reservation SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_transfer_reservation SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_upload_job SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_upload_job SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;
UPDATE tb_user_work_plan SET INSERT_DATE = INSERT_DATE + INTERVAL 9 HOUR WHERE INSERT_DATE IS NOT NULL AND INSERT_DATE >= @CUTOVER_UTC;
UPDATE tb_user_work_plan SET UPDATE_DATE = UPDATE_DATE + INTERVAL 9 HOUR WHERE UPDATE_DATE IS NOT NULL AND UPDATE_DATE >= @CUTOVER_UTC;

COMMIT;

SET SQL_SAFE_UPDATES = 1;

-- ============================================================
-- 사후 검증 (런북 §6-B) - 아래 결과를 기대값과 대조할 것
-- ============================================================
-- 1) NOW() 가 KST 인지 (현재 한국 시각과 일치해야 함)
SELECT @@session.time_zone AS sessTz, DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i') AS nowWall;

-- 2) 표본: TBM 테스트 세션 - 기대값 endedWall = '2026-08-30 10:49'
SELECT SESSION_CD, DATE_FORMAT(ENDED_AT, '%Y-%m-%d %H:%i') AS endedWall
FROM tb_tbm_session WHERE SESSION_CD = 'T202608300001022';

-- 3) 표본: 최근 출근(08-30) - 기대값 insWall = '2026-08-30 10:05' (CHECK_IN 1005 와 일치)
SELECT ATTD_ID, CHECK_IN_TIME, DATE_FORMAT(INSERT_DATE, '%Y-%m-%d %H:%i') AS insWall
FROM tb_user_attd_mgmt WHERE ATTD_ID = '2026083000061';

-- 4) 미래 시각 이상치(보정 이중 적용 의심 신호) - grantExpire 는 연차 만료예정이라 미래가 정상, 그 외 0 이어야 함
SELECT
 (SELECT COUNT(*) FROM tb_user_attd_mgmt   WHERE INSERT_DATE > NOW() + INTERVAL 5 MINUTE) AS attdFuture,
 (SELECT COUNT(*) FROM tb_tbm_session      WHERE INSERT_DATE > NOW() + INTERVAL 5 MINUTE) AS tbmFuture,
 (SELECT COUNT(*) FROM tb_user             WHERE INSERT_DATE > NOW() + INTERVAL 5 MINUTE) AS userFuture,
 (SELECT COUNT(*) FROM tb_user_work_plan   WHERE INSERT_DATE > NOW() + INTERVAL 5 MINUTE) AS planFuture;

-- 5) 행수 불변 확인(보정은 UPDATE 만 - 개수 변화가 있으면 이상)
SELECT
 (SELECT COUNT(*) FROM tb_user_work_plan) AS planCnt,
 (SELECT COUNT(*) FROM tb_user_attd_mgmt) AS attdCnt,
 (SELECT COUNT(*) FROM tb_auth_token)     AS tokenCnt;
